#!/bin/bash

if [[ ! -f ~/.gitconfig ]]; then
    echo "[git] Linking git config: ~/.gitconfig"
    ln -s ~/Config/misc/gitconfig ~/.gitconfig
fi

if [[ ! -d ~/.zsh.d ]] && [[  ! -f ~/.zshrc ]]; then
    echo "[zsh] Linking zsh config"
    ln -s ~/Config/zsh/zshrc ~/.zshrc
    ln -s ~/Config/zsh/zsh.d ~/.zsh.d
fi

if [[ ! -d ~/.vim ]] && [[  ! -f ~/.vimrc ]]; then
    echo "[vim] Linking vim config"
    ln -s ~/Config/vim/vimrc ~/.vimrc
    ln -s ~/Config/vim/vim ~/.vim
fi

if [[ ! -f ~/.tmux.conf ]]; then
    echo "[tmux] Linking tmux config: ~/.tmux.conf"
    ln -s ~/Config/misc/tmux.conf ~/.tmux.conf
fi

if [[ ! -f ~/.dir_colors ]]; then
    echo "[ls] Installing dir_colors"
    ln -s ~/Config/misc/dir_colors ~/.dir_colors
fi
