"
" Add bundles to the path
call pathogen#runtime_append_all_bundles()

" File-type highlighting and configuration.
" Run :filetype (without args) to see what you may have
" to turn on yourself, or just set them all to be sure.
au BufRead,BufNewFile *.tex setf tex
syntax on
filetype off
filetype on
filetype plugin on
filetype indent on

set nocompatible
set nofoldenable 

" The current buffer can be put to the background without writing to disk;
" When a background buffer becomes current again, marks and undo-history are remembered.
set hidden

" By default, Vim only remembers the last 20 commands and search patterns
" entered. It’s nice to boost this up: 
set history=1000

" By default, pressing <TAB> in command mode will choose the first possible
" completion with no indication of how many others there might be. The
" following configuration lets you see what your other options are: 
set wildmenu

" To have the completion behave similarly to a shell, i.e. complete only up to
" the point of ambiguity (while still showing you what your options are), also
" add the following:
set wildmode=list:longest

" These two options, when set together, will make /-style searches
" case-sensitive only if there is a capital letter in the search expression.
" *-style searches continue to be consistently case-sensitive. 
set ignorecase 
set smartcase

" A running gvim will always have a window title, but when vim is run within
" an xterm, by default it inherits the terminal’s current title. 
set title

" When the cursor is moved outside the viewport of the current window, the
" buffer is scrolled by a single line. Setting the option below will start the
" scrolling three lines before the border, keeping more context around where
" you’re working. 
set scrolloff=3

" Swap files and backups are annoying but can save you a lot of trouble.
" Rather than spreading them all around your filesystem, isolate them to a
" single directory: 
set backupdir=~/.vim/tmp/,~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set directory=~/.vim/tmp,~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp

" Intuitive backspacing in insert mode
set backspace=indent,eol,start
 

" Highlight search terms...
set hlsearch
set incsearch " ...dynamically as they are typed.

" The “Press ENTER or type command to continue” prompt is jarring and usually
" unnecessary. You can shorten command-line text and other info tokens with,
set shortmess=atI

" I Never, ever used background=light
set background=dark


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"" php
let php_htmlInStrings = 1 " use html syntax in strings
"" shell scripting
let highlight_function_name = 1


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Clickodrome binds
map  <C-s> :w!<CR>
imap <C-s> <Esc>:w!<CR>a
map  <C-t> :tabnew<CR>
imap <C-t> <Esc>:tabnew<CR>a


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Write file with sudo // Life saver !
function! Sudowq()
	exe "w !sudo tee % > /dev/null"
	exe "e!"
endfunction
nmap <F2> :call Sudowq()<CR><Enter>


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Ctags functions
let Tlist_Shutup = 1
let Tlist_WinWidth = 50
map <F3> :TlistToggle<cr>
map <esc><F3> :!/usr/bin/ctags -R --c++-kinds=+p --fields=+iaS --extra=+q .<CR>

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" bufferlist plugin
map <silent> <C-v>v :call BufferList()<CR>
map <silent> <C-v><C-v> :call BufferList()<CR>


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Use DetectIndent plugin if available
autocmd BufReadPost * 
            \ if exists(":DetectIndent") |  
            \ execute ":DetectIndent" |
            \  endif

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Make some plugins stfu
let g:gist_shutup = 1

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" spaces spaces spaces
set tabstop=4
set shiftwidth=4
set autoindent
set expandtab
autocmd FileType make     set noexpandtab
autocmd FileType python   set noexpandtab

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" I HATE HATE HATE Mouse emulation
set mouse-=a


if has("gui_running")
  colorscheme ir_black
else
  colorscheme desert
endif

" Do not load gist plugin if we can't use it
if !executable('git') || !executable('curl')
	let g:loaded_gist_vim = 1
endif

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Used for C and Hint man plugin
autocmd FileType c,cpp set ch=2
if &bg == "dark"
    hi HintHL cterm=bold ctermfg=white ctermbg=black guifg=blue3 guibg=white
else
    hi HintHL cterm=bold ctermfg=black ctermbg=white guifg=white guibg=blue3
endif

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Syntastic
let g:syntastic_enable_signs=1
let g:syntastic_disabled_filetypes = ['c', 'cpp']

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" A.vim
let g:alternateNoDefaultAlternate = 1 " Do not alternate if not found

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Source a local configuration file if available.
if filereadable(expand("~/.vimrc.local"))
  source ~/.vimrc.local
endif
