# 
# Zshrc home configs files
# Camille Moncelier <pix@devlife.org>
#
# Greatly inspired by  Bruno Bonfils, <asyd@asyd.net>
#
#

# My functions (don't forget to modify fpath before call compinit !!)
fpath=($HOME/.zsh/functions $fpath)


# in order to have many completion function run comptinstall !
autoload -U zutil
autoload -U compinit
autoload -U complist

autoload -U predict-on
zle -N predict-on
zle -N predict-off


# Activation
compinit

local os host

# Set default umask to 027, can be override by host specific resource file
umask 022

# Load System wide profile:
[ -f /etc/profile ] && source /etc/profile

# per OS resource file
os=$(uname)
[ -f "$HOME/.zsh/rc.os/${os}.zsh" ] && source "$HOME/.zsh/rc.os/${os}.zsh"

# Global resource files
for file in $HOME/.zsh/rc/*.rc; do
    source $file
done

# per host resource file
host=${$(hostname)//.*/}
if [ -f "$HOME/.zsh/rc.host/${host}.zsh" ] ; then
     source "$HOME/.zsh/rc.host/${host}.zsh"
else
    source "$HOME/.zsh/rc.host/default.zsh"
fi

# Local file
[[ -f ~/.zsh/rc.local ]] && source ~/.zsh/rc.local

# exports default languages
export LANG=en_US.utf8
export LC_COLLATE=C

# Only ask for seeing all possibilities if line would scroll off screen
LISTMAX=0

# setup prompt
autoload -U promptinit
promptinit
prompt walters

export PATH=$PATH:~/.bin
